% This script loops through the waveform_average_kinetics folder and groups
% them by experimental conditions: 
% For example:
    % DR+CNO- 1
    % CNO- 2
    % NT- 3

% The experimental condition of a cell can be uniquely determined by the date, 
% and the cell_num assigned on that day via a look-up cell_id_index table.  

% Once the waveform averages of all cells have been grouped by their
% experimental conditions, a mega waveform average will be generated by
% taking the average of all cells within each condition.

%% Experimental settings

%save results
save_results = 1;

%figure on
figure_on_unscaled = 1;
figure_on_scaled = 1;

%experiment name (correpsonding to the sheet name in the cell_id_index
% excel file)
exp_name = 'APV_24h';

%subfolder
sub = 'rise_1';

%where to save grouped files
fp_wa_group = ...,
    '/Users/wwneuro/My_Drive/Lab/Data_analysis/culture_experiments/waveform_average_by_groups/';

%experimental conditions
exp_con = {'Ctrl','APV'};

%import cell_id_index table 
fp_mini_group = '/Users/wwneuro/My_Drive/Lab/Data_analysis/culture_experiments/mini_data_by_groups/';
cd(fp_mini_group)
cell_id_index = readtable('cell_id_index.xlsx','Sheet',strcat(exp_name,'_',sub));

%location of waveform average files (per cell)
fp_wak = '/Users/wwneuro/My_Drive/Lab/Data_analysis/culture_experiments/waveform_average_kinetics/';

%% group data by condition

%pre-allocation
all_wavg = cell(1,numel(exp_con));

%loop through folder
cd(strcat(fp_wak, sub))
all_files_temp = dir;
for fi = 1:size(all_files_temp,1)
    if strcmp('.DS_Store',all_files_temp(fi).name)
        delete '.DS_Store'
        continue
    end
end

all_files = dir;
file_num = numel(all_files)-2;

for fi = 1:file_num
    curr_name = all_files(fi+2).name;
    curr_date = curr_name(1:6);
    
    cy = strcat('20',curr_date(1:2));
    cM = curr_date(3:4);
    cday = curr_date(5:6);
    
    date = datetime(strcat(cy,'-',cM,'-',cday),'InputFormat','y-M-d',...
        'Format', 'M/d/y');
    if ~(ismember(date,cell_id_index.Date))
        continue
    else
        load(all_files(fi+2).name)
        
        for ci = 1:size(wavg_per_cell{1,1},2)
            if sum(wavg_per_cell{1,1}(:,ci)) == 0
                continue
            else
                if isempty(find(cell_id_index.Date == date & cell_id_index.Cell_num == ci,1))
                    continue
                else
                
                    row = find(cell_id_index.Date == date & cell_id_index.Cell_num == ci);
                    cond_i = cell_id_index{row,'Cat'};
                    cell_ID = cell_id_index{row,'Cell_ID'};
                    all_wavg{1,cond_i}(:,cell_ID) = wavg_per_cell{1,1}(:,ci);
                end
            end
        end
    end
        
end

%% calculate meta average
%pre-allocation
all_meta_wavg = cell(1,numel(exp_con));

%calculate average for each row
%The order of experimental conditions follows the order in exp_con.
for ei = 1:numel(exp_con)
    for ri = 1:size(all_wavg{1,ei},1)
        all_meta_wavg{1,ei}(ri,1) = mean(all_wavg{1,ei}(ri,:),'omitnan');
    end
end

%% Scale peaks: scale condition2 to condition1
% usually scale condition 2 to condition 1 
% (double check the order in exp_con)


%cultured neuron + APV color scheme
color1 = '#D095DB'; 
color2 = '#573E5C';

%define conditions
condition1 = all_meta_wavg{1,1};
condition2 = all_meta_wavg{1,2};

[peak_cond1, peak_ind_cond1] = min(condition1);
[peak_cond2, peak_ind_cond2] = min(condition2);

%the entire waveform scaled by peak amplitude (will get similar results if 
% using the scaling factor calcuated from the cumulative population, faster this way)

scale_factor = mean(condition1((peak_ind_cond1-1):(peak_ind_cond1+1),1))/...,
    mean(condition2((peak_ind_cond2-1):(peak_ind_cond2+1),1));

condition2_scaled = NaN(size(condition1,1),1);
diff = size(condition1,1)-size(condition2,1);

if diff >=0
    condition2_scaled(diff+1:end) = condition2 .* scale_factor;
else
    condition2_scaled = condition2(abs(diff)+1 : end) .* scale_factor;
end
    

%plotting unscaled

plot_range = (10:150);
y_limit = [-Inf Inf];

if figure_on_unscaled == 1
    figure();
    plot(condition1(plot_range),'Color',color1,'LineWidth',4)
    hold on
    %plot(condition3(plot_range),'Color',color3,'LineWidth',4)   
    plot(condition2(plot_range),'Color',color2,'LineWidth',4)
    %hold on
    %plot(meta_ave.DR_CNO_24(20:110),'Color',[0.27 0.51 0.71],'LineWidth',4)
    %draw scale
    scale_x_start = plot_range(end)-30;
    plot([scale_x_start; scale_x_start+10],[-10; -10], '-k',[scale_x_start;scale_x_start],[-10; -5], '-k', 'LineWidth',2)
    text(scale_x_start, -8, '5 pA', 'HorizontalAlignment', 'right')
    text(scale_x_start+5, -11, '2 ms', 'HorizontalAlignment', 'center')
    
    title('unscaled')
    ylim(y_limit)
    
    box off
    hold off
end

    %plotting scaled
if figure_on_scaled == 1    
    figure();
    plot(condition1(plot_range),'Color',color1,'LineWidth',4)
    hold on
    plot(condition2_scaled(plot_range),'Color',color2,'LineWidth',4)
%     hold on
%     plot(shk3_scaled(20:110),'Color',[0.27 0.51 0.71],'LineWidth',4)
    title('scaled')
    ylim(y_limit)
    box off
    hold off
end


%% save to file

if save_results == 1
    cd(strcat(fp_wa_group, sub))
    save(strcat(exp_name,'.mat'),'all_wavg','all_meta_wavg','scale_factor','exp_con')
end
